version: '3.8'

services:
  db:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_DB: token_service
      POSTGRES_USER: token_user
      POSTGRES_PASSWORD: token_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U token_user -d token_service"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://token_user:token_password@db:5432/token_service
      - DEBUG=True
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
